FROM continuumio/miniconda:latest

WORKDIR /app
COPY opanalytics_mac.yml ./
RUN conda env create -f opanalytics_mac.yml
COPY /Models/*.py ./
COPY /Models/boot.sh ./

RUN chmod +x boot.sh

#activate env
RUN echo "source activate opanalytics" > ~/.bashrc
ENV PATH /opt/conda/envs/opanalytics/bin:$PATH


ENTRYPOINT ["./boot.sh"]