CREATE TABLE "indici"(
id INTEGER PRIMARY KEY AUTOINCREMENT,
"Data" TEXT,
"SP_500" DOUBLE,
"FTSE_MIB" DOUBLE,
"GOLD_SPOT" DOUBLE,
"MSCI_EM" DOUBLE,
"MSCI_EURO" DOUBLE,
"All_Bonds" DOUBLE,
"US_Treasury" DOUBLE)